# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: releases-docker.jfrog.io/jfrog/jfrog-cli-v2-jf
    steps:
      - name : JFrog cli install and setup 
        run: |
         jf -v
